# SPDX-FileCopyrightText: Copyright 2024 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0

src = ["resources"]
exclude = ["venv*", "unit_tests", "config", "tests", "doc"]
line-length = 120
respect-gitignore = true

[lint]
ignore = ["D415", "D400", "D213", "D212", "D203"]
#typing-modules = [""]
select = [
     "F", # pyflakes
    "E", "W", # Pycodestyle
    "I001", # isort
    "D",  # docstring checker
]
[format]
docstring-code-format = true
exclude = ["D213", "D212", "D211", "D200"]
indent-style = "space"
#skip-magic-trailing-comma = true

# D200 fits-on-one-line
# D211 no-blank-line-before-class
# D212 multi-line-summary-first-line
# D213 multi-line-summary-second-line
# D400 First line should end with a period
# D415 ends-in-punctuation
# because of RF # fixable with # noqa: D417 on the function.
# spaces and D203, 211 are incompatible.
