# SPDX-FileCopyrightText: Copyright 2024 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0

name: Check code quality

on:
  push:
    branches:
      - main
      - pq_migration2
  pull_request:
    branches:
      - main
      - pq_migration2
  workflow_dispatch:

jobs:
  ruff_lint:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/cmp-test-dev:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Code style
        run: ruff check

  license_check:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/cmp-test-dev:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: License check
        run: reuse lint

  rf_style_check:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/cmp-test-dev:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: RobotFramework style check
        run: robocop --report rules_by_error_type

  spelling_check:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/cmp-test-dev:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Spelling checker
        run:  codespell . --check-filenames --skip=*.html,*.pem,*.xml,*venv*,*fips/*.py,*data/*,*/liboqs-python/*,*doc/*,*data/pqc-certificates/*,*data/stats,*/tests_rsa_kem/*

  pylint:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/cmp-test-dev:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Pylint check
        run: pylint --fail-under=9.38 resources

  unit_test:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/cmp-test-dev:latest
      env:
        OQS_INSTALL_PATH: "/root/_oqs"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Unit tests
        run: PYTHONPATH=./resources python3 -m unittest discover -s unit_tests

  type_check:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/cmp-test-dev:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Pyright check
        run: PYTHONPATH=./resources pyright ./resources