name: Docker Unit tests

on: [push, pull_request]

jobs:
  build_and_run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t unittest-image -f data/dockerfiles/Dockerfile.unittest .

      - name: Run Docker container
        run: |
          docker run --rm -t --workdir=/app unittest-image
